<div>
    @if(session('success')) <div class="mb-4 rounded-lg bg-emerald-500/10 px-4 py-3 text-emerald-300">{{ session('success') }}</div> @endif
    <div class="rounded-xl border border-dark-700 bg-dark-800 p-4">
        <div class="flex justify-between"><div><p class="font-medium text-gray-200">Saved categories</p><p class="text-xs text-gray-500">Manage categories used for expenses.</p></div><button type="button" wire:click="create" class="rounded-lg bg-primary px-3 py-2 text-sm text-white">+ Add category</button></div>
        <div class="mt-4 flex flex-wrap gap-2">@forelse($categories as $category)<button type="button" wire:click="edit({{ $category->id }})" class="rounded-full border border-dark-600 px-3 py-1.5 text-sm text-gray-300">{{ $category->name }} ({{ $category->types->count() }})</button>@empty<p class="text-sm text-gray-500">No saved categories yet.</p>@endforelse</div>
    </div>
    @if($open)
    <div class="fixed inset-0 z-[70] overflow-y-auto bg-black/75 p-4"><div class="flex min-h-full items-center justify-center"><form wire:submit="save" class="w-full max-w-2xl rounded-xl border border-dark-600 bg-dark-800 p-6">
        <div class="flex justify-between"><h2 class="font-mono text-xl text-white">{{ $categoryId ? 'Edit category' : 'Add category' }}</h2><button type="button" wire:click="$set('open', false)" class="text-xl text-gray-400">×</button></div>
        <div class="mt-5 space-y-5"><div><label class="text-sm text-gray-300">Category title</label><input wire:model="name" class="mt-1 w-full rounded-lg border border-dark-600 bg-dark-900 px-3 py-2.5 text-white">@error('name')<p class="text-xs text-danger">{{ $message }}</p>@enderror</div>
        <div><div class="flex justify-between"><label class="text-sm text-gray-300">Expense types</label><button type="button" wire:click="addType" class="text-xs text-primary-light">+ Add type</button></div>@foreach($expenseTypes as $index => $type)<div wire:key="expense-type-{{ $index }}" class="mt-2 flex gap-2"><input wire:model="expenseTypes.{{ $index }}" placeholder="e.g. Filling Charges" class="w-full rounded-lg border border-dark-600 bg-dark-900 px-3 py-2 text-white"><button type="button" wire:click="removeType({{ $index }})" class="text-danger">×</button></div>@endforeach @error('expenseTypes.0')<p class="text-xs text-danger">{{ $message }}</p>@enderror</div>
        <div><label class="text-sm text-gray-300">Responsible staff</label><div class="mt-2 flex flex-wrap gap-3">@forelse($staff as $member)<label class="flex gap-2 text-sm text-gray-300"><input type="checkbox" wire:model="staffIds" value="{{ $member->id }}">{{ $member->name }}</label>@empty<p class="text-sm text-gray-500">Add Staff members first.</p>@endforelse</div></div>
        <div class="grid gap-4 sm:grid-cols-2"><label class="text-sm text-gray-300">Expense types display<select wire:model="expense_type_display" class="mt-1 w-full rounded-lg bg-dark-900 p-2 text-white"><option value="tags">Tags</option><option value="dropdown">Dropdown</option></select></label><label class="text-sm text-gray-300">Staff display<select wire:model="staff_display" class="mt-1 w-full rounded-lg bg-dark-900 p-2 text-white"><option value="tags">Tags</option><option value="dropdown">Dropdown</option></select></label></div><label class="flex gap-2 text-sm text-gray-300"><input type="checkbox" wire:model="is_active">Active category</label></div>
        <div class="mt-6 flex justify-end gap-3"><button type="button" wire:click="$set('open', false)" class="text-gray-400">Cancel</button><button class="rounded-lg bg-primary px-5 py-2.5 text-white">Save category</button></div>
    </form></div></div>
    @endif
</div>
