<div>
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><div class="flex items-center gap-2 text-xs text-gray-500"><a href="{{ route('admin.dashboard') }}" class="hover:text-gray-300">Dashboard</a><span>›</span><span>Indus Gas</span><span>›</span><span class="text-gray-300">Expenses</span></div><h1 class="mt-2 text-2xl font-mono font-bold uppercase tracking-wider text-white">Expenses</h1><p class="mt-1 text-sm text-gray-500">Add and review business expenses from one place.</p></div>
        <button type="button" wire:click="openForm" class="rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-white hover:bg-primary-hover">+ Add expense</button>
    </div>

    @if(session('success'))<div class="mt-5 rounded-xl border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-300">{{ session('success') }}</div>@endif

    <section class="mt-7 overflow-hidden rounded-xl border border-dark-700 bg-dark-800"><div class="flex items-center justify-between border-b border-dark-700 px-5 py-4"><div><h2 class="font-mono font-semibold text-white">Expense records</h2><p class="mt-1 text-xs text-gray-500">Saved expenses from your business.</p></div><span class="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary-light">{{ $expenses->count() }} records</span></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b border-dark-700 bg-dark-900/60 text-xs uppercase tracking-wider text-gray-500"><tr><th class="px-5 py-3">Date</th><th class="px-5 py-3">Category</th><th class="px-5 py-3">Expense type</th><th class="px-5 py-3">Paid / responsible</th><th class="px-5 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-dark-700">@forelse($expenses as $expense)<tr class="text-gray-300"><td class="px-5 py-4">{{ $expense->expense_date->format('d M Y') }}</td><td class="px-5 py-4"><span class="rounded-full bg-primary/10 px-2.5 py-1 text-xs text-primary-light">{{ $expense->category->name }}</span></td><td class="px-5 py-4">{{ $expense->type?->name }}</td><td class="px-5 py-4">{{ $expense->responsibleStaff?->name ?? ($expense->payer_amounts ? collect($expense->payer_amounts)->keys()->map(fn ($id) => optional(\App\Models\IndusGas\Staff::find($id))->name)->filter()->join(', ') : '—') }}</td><td class="px-5 py-4 text-right font-mono text-white">PKR {{ number_format($expense->amount, 2) }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-gray-500">No expenses saved yet. Use “Add expense” to create your first one.</td></tr>@endforelse</tbody></table></div></section>

    <div class="mt-6"><livewire:admin.indus-gas.expenses.category-manager /></div>

    @if($showForm)
        <div class="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-3 sm:p-6"><div class="flex min-h-full items-start justify-center py-3 sm:items-center"><form wire:submit="save" class="w-full max-w-4xl rounded-2xl border border-dark-600 bg-dark-800 shadow-2xl"><div class="flex items-start justify-between border-b border-dark-700 px-6 py-4 sm:px-8"><div><p class="text-xs font-semibold uppercase tracking-wider text-primary-light">Add expense</p><h2 class="mt-1 font-mono text-xl font-semibold text-white">Expense details</h2><p class="mt-1 text-sm text-gray-500">Select a category. The form changes based on its saved settings.</p></div><button type="button" wire:click="closeForm" class="text-2xl text-gray-500 hover:text-white">×</button></div>
            <div class="space-y-6 p-6 sm:px-8"><div><div class="flex items-center justify-between"><label class="text-sm font-medium text-gray-200">Expense category</label><button type="button" wire:click="openCategoryManager" class="text-xs font-medium text-primary-light hover:text-white">+ Add category</button></div><p class="mt-1 text-xs text-gray-500">Bike and Car remain separate fuel-calculation forms for now.</p><div class="mt-3 flex flex-wrap gap-2">@forelse($categories as $category)<button type="button" wire:click="selectCategory({{ $category->id }})" class="rounded-lg border px-4 py-2.5 text-sm font-medium {{ $expenseCategoryId === $category->id ? 'border-primary bg-primary/15 text-primary-light' : 'border-dark-600 bg-dark-900 text-gray-400' }}">{{ $category->name }}</button>@empty<p class="text-sm text-gray-500">Create an expense category first.</p>@endforelse<button type="button" wire:click="selectDefaultVehicle('bike')" class="rounded-lg border border-dark-600 bg-dark-900 px-4 py-2.5 text-sm font-medium text-gray-400">Bike</button><button type="button" wire:click="selectDefaultVehicle('car')" class="rounded-lg border border-dark-600 bg-dark-900 px-4 py-2.5 text-sm font-medium text-gray-400">Car</button></div>@error('expenseCategoryId')<p class="mt-2 text-xs text-danger">{{ $message }}</p>@enderror</div>

                @if($selectedCategory)
                    <div class="space-y-6 border-t border-dark-700 pt-6"><div><label class="text-sm font-medium text-gray-200">Expense type</label>@if($selectedCategory->expense_type_display === 'dropdown')<select wire:model="expenseTypeId" class="mt-2 block w-full max-w-md rounded-lg border border-dark-600 bg-dark-900 px-3 py-2.5 text-sm text-white"><option value="">Select expense type</option>@foreach($selectedCategory->types as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select>@else<div class="mt-3 flex flex-wrap gap-2">@foreach($selectedCategory->types as $type)<button type="button" wire:click="$set('expenseTypeId', {{ $type->id }})" class="rounded-lg border px-4 py-2.5 text-sm font-medium {{ $expenseTypeId === $type->id ? 'border-primary bg-primary/15 text-primary-light' : 'border-dark-600 bg-dark-900 text-gray-400' }}">{{ $type->name }}</button>@endforeach</div>@endif @error('expenseTypeId')<p class="mt-2 text-xs text-danger">{{ $message }}</p>@enderror</div>

                    @if($selectedCategory->requires_cylinder_quantity)<div><label class="text-sm font-medium text-gray-200">Total number of cylinders</label><input type="number" min="1" wire:model="cylinderQuantity" placeholder="For example: 50" class="mt-2 block w-full max-w-sm rounded-lg border border-dark-600 bg-dark-900 px-3 py-2.5 text-sm text-white">@error('cylinderQuantity')<p class="mt-2 text-xs text-danger">{{ $message }}</p>@enderror</div>@endif

                    <div class="border-t border-dark-700 pt-6">@if($selectedCategory->staff_selection_mode === 'multiple_payers')<div class="flex items-end justify-between"><div><label class="text-sm font-medium text-gray-200">Who paid?</label><p class="mt-1 text-xs text-gray-500">Select one or more people, then enter each paid amount.</p></div></div>@if($selectedCategory->staff_display === 'dropdown')<select multiple wire:model="selectedStaffIds" class="mt-3 block w-full max-w-md rounded-lg border border-dark-600 bg-dark-900 px-3 py-2.5 text-sm text-white">@foreach($selectedCategory->staff as $staff)<option value="{{ $staff->id }}">{{ $staff->name }}</option>@endforeach</select>@else<div class="mt-3 flex flex-wrap gap-2">@foreach($selectedCategory->staff as $staff)<button type="button" wire:click="togglePayer({{ $staff->id }})" class="rounded-full border px-4 py-2 text-sm font-medium {{ in_array($staff->id, $selectedStaffIds, true) ? 'border-primary bg-primary/15 text-primary-light' : 'border-dark-600 bg-dark-900 text-gray-400' }}">{{ $staff->name }}</button>@endforeach</div>@endif @error('selectedStaffIds')<p class="mt-2 text-xs text-danger">{{ $message }}</p>@enderror <div class="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">@foreach($selectedCategory->staff->whereIn('id', $selectedStaffIds) as $staff)<div><label class="text-sm font-medium text-gray-200">{{ $staff->name }} paid</label><div class="relative mt-2"><span class="absolute inset-y-0 left-0 flex items-center pl-3 text-sm text-gray-500">PKR</span><input type="number" min="0" step="0.01" wire:model="payerAmounts.{{ $staff->id }}" class="block w-full rounded-lg border border-dark-600 bg-dark-900 py-2.5 pl-12 pr-3 text-sm text-white"></div>@error('payerAmounts.'.$staff->id)<p class="mt-1 text-xs text-danger">{{ $message }}</p>@enderror</div>@endforeach</div>@else<label class="text-sm font-medium text-gray-200">Who was responsible?</label><p class="mt-1 text-xs text-gray-500">Select one person and enter the total expense amount.</p><select wire:model="responsibleStaffId" class="mt-3 block w-full max-w-md rounded-lg border border-dark-600 bg-dark-900 px-3 py-2.5 text-sm text-white"><option value="">Select staff member</option>@foreach($selectedCategory->staff as $staff)<option value="{{ $staff->id }}">{{ $staff->name }}</option>@endforeach</select>@error('responsibleStaffId')<p class="mt-2 text-xs text-danger">{{ $message }}</p>@enderror <div class="mt-4 max-w-sm"><label class="text-sm font-medium text-gray-200">Expense amount</label><div class="relative mt-2"><span class="absolute inset-y-0 left-0 flex items-center pl-3 text-sm text-gray-500">PKR</span><input type="number" min="0" step="0.01" wire:model="amount" class="block w-full rounded-lg border border-dark-600 bg-dark-900 py-2.5 pl-12 pr-3 text-sm text-white"></div>@error('amount')<p class="mt-1 text-xs text-danger">{{ $message }}</p>@enderror</div>@endif</div>
                    <div class="border-t border-dark-700 pt-6"><label class="text-sm font-medium text-gray-200">Expense date</label><input type="date" wire:model="expenseDate" class="mt-2 block w-full max-w-sm rounded-lg border border-dark-600 bg-dark-900 px-3 py-2.5 text-sm text-white">@error('expenseDate')<p class="mt-2 text-xs text-danger">{{ $message }}</p>@enderror</div></div>
                @elseif($defaultVehicleForm)
                    <div x-data="{distance:'',average:'',rate:''}" class="space-y-5 border-t border-dark-700 pt-6"><p class="text-sm text-gray-400">{{ ucfirst($defaultVehicleForm) }} fuel calculator (kept as the existing default form).</p><div class="grid gap-4 sm:grid-cols-3"><label class="text-sm text-gray-300">Distance travelled (km)<input type="number" x-model="distance" class="mt-2 w-full rounded-lg border border-dark-600 bg-dark-900 px-3 py-2.5 text-white"></label><label class="text-sm text-gray-300">Fuel average (km/litre)<input type="number" step="0.01" x-model="average" class="mt-2 w-full rounded-lg border border-dark-600 bg-dark-900 px-3 py-2.5 text-white"></label><label class="text-sm text-gray-300">Fuel price per litre (PKR)<input type="number" step="0.01" x-model="rate" class="mt-2 w-full rounded-lg border border-dark-600 bg-dark-900 px-3 py-2.5 text-white"></label></div><div class="rounded-lg border border-primary/25 bg-primary/10 p-4 text-primary-light">Fuel cost: <span class="font-mono text-white" x-text="distance && average && rate ? 'PKR ' + ((distance / average) * rate).toFixed(2) : 'Enter trip details'"></span></div></div>
                @else
                    <div class="rounded-xl border border-dashed border-dark-600 bg-dark-900/40 px-5 py-8 text-center text-sm text-gray-500">Select an expense category to see its form.</div>
                @endif
            </div><div class="flex justify-end gap-3 border-t border-dark-700 px-6 py-5 sm:px-8"><button type="button" wire:click="closeForm" class="rounded-lg px-4 py-2 text-sm text-gray-400">Cancel</button><button type="submit" @disabled(! $selectedCategory) class="rounded-lg bg-primary px-5 py-2.5 text-sm font-medium text-white disabled:cursor-not-allowed disabled:bg-dark-700">Save expense</button></div></form></div></div>
    @endif
</div>
