<div>
    <div class="flex items-center gap-2 mb-2 text-xs text-gray-500"><a wire:navigate href="{{ route('admin.dashboard') }}" class="hover:text-gray-300">Dashboard</a><span>›</span><span>Indus Gas</span><span>›</span><span class="text-gray-300">LPG Plant</span></div>
    <div class="flex flex-col justify-between gap-4 mb-8 sm:flex-row sm:items-start"><div><h1 class="text-2xl font-mono font-bold tracking-wider text-white uppercase">LPG Plant</h1><p class="mt-1 text-gray-500">Track daily market rates, filling quantities, purchase cost, and payment status.</p></div><button type="button" wire:click="openCreateModal" class="px-4 py-2.5 text-sm font-medium text-white rounded-lg bg-primary hover:bg-primary-hover">Add daily entry</button></div>

    @if(session('success'))<div class="px-4 py-3 mb-5 text-sm border rounded-lg bg-emerald-500/10 border-emerald-500/30 text-emerald-300">{{ session('success') }}</div>@endif

    <form action="{{ route('admin.indus-gas.lpg-plant.report') }}" method="GET" class="flex flex-col gap-4 p-5 mb-6 border rounded-xl bg-dark-800 border-dark-700 sm:flex-row sm:items-end">
        <div><label class="block mb-1 text-xs text-gray-400">Report from</label><input type="date" name="from" wire:model="reportFrom" required class="w-full px-3 py-2 text-white border rounded-lg bg-dark-900 border-dark-600"></div>
        <div><label class="block mb-1 text-xs text-gray-400">Report to</label><input type="date" name="to" wire:model="reportTo" required class="w-full px-3 py-2 text-white border rounded-lg bg-dark-900 border-dark-600"></div>
        <button class="px-4 py-2 text-sm font-medium text-white rounded-lg bg-dark-700 hover:bg-dark-600">Download rate PDF</button>
        <p class="text-xs text-gray-500 sm:pb-2">PDF includes date, per-kg rate, and 45.4 kg cylinder rate only.</p>
    </form>

    <div class="overflow-hidden border rounded-xl bg-dark-800 border-dark-700"><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-dark-700/50"><tr class="text-xs uppercase text-gray-400"><th class="px-5 py-3">Date</th><th class="px-5 py-3">Rate</th><th class="px-5 py-3">Cylinders filled</th><th class="px-5 py-3 text-right">Filling charges</th><th class="px-5 py-3 text-right">Total cost</th><th class="px-5 py-3">Payment</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-dark-700">
        @forelse($entries as $entry)<tr class="text-sm"><td class="px-5 py-4 font-medium text-white whitespace-nowrap">{{ $entry->entry_date->format('d M Y') }}</td><td class="px-5 py-4 leading-6 text-gray-300"><span class="block">11.8 kg: Rs. {{ number_format($entry->rate_11_8_kg, 2) }}</span><span class="block text-xs text-gray-500">Per kg: Rs. {{ number_format($entry->rate_per_kg, 2) }} · 45.4 kg: Rs. {{ number_format($entry->rate_45_4_kg, 2) }}</span></td><td class="px-5 py-4 leading-6 text-gray-300"><span class="block">45.4 kg: {{ $entry->filled_45_4_kg_cylinders }}</span><span class="block text-xs text-gray-500">11.8 kg: {{ $entry->filled_11_8_kg_cylinders }}</span></td><td class="px-5 py-4 font-mono text-right text-gray-300 whitespace-nowrap">Rs. {{ number_format($entry->filling_charges, 2) }}</td><td class="px-5 py-4 font-mono font-medium text-right text-white whitespace-nowrap">Rs. {{ number_format($entry->total_cost, 2) }}</td><td class="px-5 py-4"><span class="text-xs {{ $entry->is_paid ? 'text-emerald-400' : 'text-amber-300' }}">{{ $entry->is_paid ? 'Paid' : 'Unpaid' }}</span></td><td class="px-5 py-4 text-right"><a wire:navigate href="{{ route('admin.indus-gas.lpg-plant.edit', $entry) }}" class="text-sm text-primary-light hover:text-white">Edit</a></td></tr>@empty<tr><td colspan="7" class="px-5 py-14 text-center text-gray-500">No LPG Plant entries yet. Add the first daily rate.</td></tr>@endforelse
    </tbody></table></div>@if($entries->hasPages())<div class="px-5 py-4 border-t border-dark-700">{{ $entries->links() }}</div>@endif</div>

    @if($showCreateModal)
        <div class="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="lpg-entry-title">
            <button type="button" wire:click="closeCreateModal" class="absolute inset-0 bg-black/70" aria-label="Close add daily entry form"></button>
            <form wire:submit="save" class="relative z-10 w-full max-w-4xl max-h-[calc(100vh-2rem)] overflow-y-auto p-6 space-y-6 border shadow-2xl rounded-xl bg-dark-800 border-dark-700">
                <div class="flex items-start justify-between gap-4"><div><h2 id="lpg-entry-title" class="text-xl font-mono font-bold text-white">Add LPG Plant daily entry</h2><p class="mt-1 text-sm text-gray-500">Enter the 11.8 kg plant rate; all other values are calculated automatically.</p></div><button type="button" wire:click="closeCreateModal" class="text-2xl leading-none text-gray-400 hover:text-white" aria-label="Close">×</button></div>
                <div class="grid gap-6 lg:grid-cols-2"><div class="space-y-5"><div><label class="block mb-1 text-sm text-gray-300">Date <span class="text-red-400">*</span></label><input type="date" wire:model="entry_date" class="w-full px-3 py-2.5 text-white border rounded-lg bg-dark-900 border-dark-600">@error('entry_date')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror<p class="mt-1 text-xs text-gray-500">Sunday is an off day.</p></div><div><label class="block mb-1 text-sm text-gray-300">Rate for 11.8 kg cylinder (PKR) <span class="text-red-400">*</span></label><input type="number" min="0.0001" step="0.0001" wire:model.live="rate_11_8_kg" placeholder="e.g. 4630" class="w-full px-3 py-2.5 text-white border rounded-lg bg-dark-900 border-dark-600">@error('rate_11_8_kg')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div><div><label class="block mb-1 text-sm text-gray-300">Filled 45.4 kg cylinders <span class="text-red-400">*</span></label><input type="number" min="0" step="1" wire:model.live="filled_45_4_kg_cylinders" class="w-full px-3 py-2.5 text-white border rounded-lg bg-dark-900 border-dark-600">@error('filled_45_4_kg_cylinders')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div><div><label class="block mb-1 text-sm text-gray-300">Filled 11.8 kg cylinders <span class="text-gray-500">(optional)</span></label><input type="number" min="0" step="1" wire:model.live="filled_11_8_kg_cylinders" class="w-full px-3 py-2.5 text-white border rounded-lg bg-dark-900 border-dark-600">@error('filled_11_8_kg_cylinders')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div><label class="flex items-center gap-3 text-sm text-gray-300"><input type="checkbox" wire:model="is_paid" class="rounded border-dark-600 bg-dark-900 text-primary"><span>Marked as paid</span></label></div>
                    <div class="p-5 border rounded-xl bg-dark-900/50 border-dark-700"><h3 class="font-mono text-white">Calculation preview</h3>@if($preview)<dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-gray-400">Rate per kg</dt><dd class="font-mono text-white">Rs. {{ number_format($preview['rate_per_kg'], 4) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-400">Rate for 45.4 kg</dt><dd class="font-mono text-white">Rs. {{ number_format($preview['rate_45_4_kg'], 4) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-400">LPG cost</dt><dd class="font-mono text-white">Rs. {{ number_format($preview['lpg_cost'], 2) }}</dd></div><div class="flex justify-between gap-4"><dt class="text-gray-400">Filling charges</dt><dd class="font-mono text-white">Rs. {{ number_format($preview['filling_charges'], 2) }}</dd></div><div class="flex justify-between gap-4 pt-4 border-t border-dark-700"><dt class="font-medium text-white">Total cost</dt><dd class="font-mono font-bold text-primary-light">Rs. {{ number_format($preview['total_cost'], 2) }}</dd></div></dl><p class="mt-5 text-xs leading-5 text-gray-500">Rs. 10 per 45.4 kg cylinder and Rs. 8 per 11.8 kg cylinder.</p>@else<p class="mt-5 text-sm text-gray-500">Enter the 11.8 kg rate to view the automatic calculation.</p>@endif</div></div>
                <div class="flex justify-end gap-3"><button type="button" wire:click="closeCreateModal" class="px-5 py-2.5 text-gray-400 hover:text-white">Cancel</button><button class="px-5 py-2.5 text-sm font-medium text-white rounded-lg bg-primary hover:bg-primary-hover">Save entry</button></div>
            </form>
        </div>
    @endif
</div>
