<div>
    <div class="flex items-center gap-2 text-xs text-gray-500 mb-2"><a href="{{ route('admin.indus-gas.settings.index') }}" wire:navigate class="hover:text-gray-300">Indus Gas Settings</a><span>›</span><span class="text-gray-300">Business Profile</span></div>
    <div class="mb-8"><h1 class="text-2xl font-mono font-bold text-white uppercase tracking-wider">Business Profile</h1><p class="text-gray-500 mt-1">This information will appear on future Indus Gas invoices and ledgers.</p></div>
    @if (session('success'))<div class="mb-6 max-w-3xl bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 rounded-lg px-4 py-3 text-sm">{{ session('success') }}</div>@endif
    <form wire:submit="save" class="max-w-3xl space-y-6">
        <div class="bg-dark-800 border border-dark-700 rounded-xl p-6 space-y-5">
            <h2 class="text-lg font-mono font-semibold text-white">Company Details</h2>
            <div><label class="block text-sm text-gray-300 mb-1.5">Business Name <span class="text-red-400">*</span></label><input wire:model="name" class="w-full bg-dark-700 border border-dark-600 rounded-lg px-4 py-2.5 text-white">@error('name')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div>
            <div class="grid sm:grid-cols-2 gap-5"><div><label class="block text-sm text-gray-300 mb-1.5">Phone</label><input wire:model="phone" type="tel" class="w-full bg-dark-700 border border-dark-600 rounded-lg px-4 py-2.5 text-white">@error('phone')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div><div><label class="block text-sm text-gray-300 mb-1.5">Email</label><input wire:model="email" type="email" class="w-full bg-dark-700 border border-dark-600 rounded-lg px-4 py-2.5 text-white">@error('email')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div></div>
            <div class="grid sm:grid-cols-2 gap-5"><div><label class="block text-sm text-gray-300 mb-1.5">NTN</label><input wire:model="ntn" class="w-full bg-dark-700 border border-dark-600 rounded-lg px-4 py-2.5 text-white">@error('ntn')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div><div><label class="block text-sm text-gray-300 mb-1.5">City</label><input wire:model="city" class="w-full bg-dark-700 border border-dark-600 rounded-lg px-4 py-2.5 text-white">@error('city')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div></div>
            <div><label class="block text-sm text-gray-300 mb-1.5">Address</label><textarea wire:model="address" rows="3" class="w-full bg-dark-700 border border-dark-600 rounded-lg px-4 py-2.5 text-white"></textarea>@error('address')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div>
        </div>
        <div class="bg-dark-800 border border-dark-700 rounded-xl p-6 space-y-5"><h2 class="text-lg font-mono font-semibold text-white">Invoice Preferences</h2><div><label class="block text-sm text-gray-300 mb-1.5">Invoice Prefix <span class="text-red-400">*</span></label><input wire:model="invoice_prefix" maxlength="20" class="w-full bg-dark-700 border border-dark-600 rounded-lg px-4 py-2.5 text-white"><p class="text-xs text-gray-500 mt-1">Example: IG-0001</p>@error('invoice_prefix')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div><div><label class="block text-sm text-gray-300 mb-1.5">Invoice Footer</label><textarea wire:model="invoice_footer" rows="3" class="w-full bg-dark-700 border border-dark-600 rounded-lg px-4 py-2.5 text-white"></textarea>@error('invoice_footer')<p class="mt-1 text-sm text-red-400">{{ $message }}</p>@enderror</div></div>
        <button class="bg-primary hover:bg-primary-hover text-white font-medium rounded-lg px-6 py-2.5"><span wire:loading.remove wire:target="save">Save Profile</span><span wire:loading wire:target="save">Saving...</span></button>
    </form>
</div>
